Develop
se-timofeev/java-explore-with-me pull request #1
Opened 2022-11-30 19:44 UTC by se-timofeev

2022-12-01 18:14 UTC, litvitnik requested changes

2022-12-01 18:14 UTC, litvitnik commented on main/src/main/java/ru/practicum/explore/with/me/service/StatServiceImpl.java
> +        for (StatsHitDto statsHitDto : statsHitDtoList) {
Для такого случая критически важно завести отдельный эндпоинт статистики, который принимал бы List этих StatsHit, потому что везде, где можно провести запрос на эндпоинт/запрос в базу сразу на всю коллекцию - надо так и поступать. Это обусловлено тем, что накладные расходы на каждый отдельный запрос несоизмеримо высоки по сравнению с реальной нагрузкой при проведении какой-то операции с сущностью. Очень грубо говоря, реальная нагрузка при обработке каждого отдельного объекта это, пускай, 1% нагрузки, а остальные 99 - это расходы на создание запроса, проведение его по всем уровням, возвращение ответа обратно, возвращение подключения в пул и так далее. Поэтому во всех случаях в проекте, если они еще есть, на всякий случай перепроверь, что ни к какому эндпоинту или ни к какому репозиторию ты не обращаешься в цикле :)

2022-12-01 18:14 UTC, litvitnik commented on stats/src/main/resources/schema.sql
> +    uri       varchar(255)
Однажды может так случиться, что в зависимости от хоста, uri будет длиннее

2022-12-01 18:14 UTC, litvitnik commented on stats/src/main/resources/schema.sql
> +    ip        varchar(255),
А вот у ip ограничение куда более компактное - можешь поставить сюда максимально допустимую длину IPv6 адреса

2022-12-02 14:28 UTC, se-timofeev commented on stats/src/main/java/ru/practicum/explore/with/me/controller/StatController.java
> +        log.info("getViewStats start {}, end, uris {},isUnique{{", start, end, uris, isUnique);
исправил.

2022-12-02 14:31 UTC, se-timofeev commented on main/src/main/java/ru/practicum/explore/with/me/service/RequestsServiceImpl.java
> +            throw new ValidationException("events are succeeded the limit", event.getParticipantLimit().toString());
исправил.

2022-12-02 14:42 UTC, se-timofeev commented on stats/src/main/resources/schema.sql
> +    ip        varchar(255),
исправил, максимум для [IPv6 может быть 45 ](https://stackoverflow.com/questions/166132/maximum-length-of-the-textual-representation-of-an-ipv6-address)

2022-12-02 14:44 UTC, se-timofeev commented on stats/src/main/resources/schema.sql
> +    uri       varchar(255)
исправил, по стандарту максимум 2048

2022-12-02 16:07 UTC, se-timofeev commented on main/src/main/java/ru/practicum/explore/with/me/service/StatServiceImpl.java
> +        for (StatsHitDto statsHitDto : statsHitDtoList) {
в сервисе статистики добавил новый эндпойнт hits, принимающий  List<StatHitDto> hitsDto, с дальнейшем сохранением в слое БД statRepository.saveAll(hits)

2022-12-07 14:08 UTC, merged